### A Pluto.jl notebook ###
# v1.0.3

using Markdown
using InteractiveUtils

# ╔═╡ 859724e0-09cd-48e1-9f82-bb91cb1ac913
begin
import Pkg
    Pkg.activate(@__DIR__)
end

# ╔═╡ 6ebac3b2-1c48-4e4b-bc10-1e180a81a824
begin
using DiscreteSim
    using PlutoUI
    using Plots
    using Statistics
    using Printf
    using Dates
end

# ╔═╡ 19b5fdb4-5c36-4761-a2ed-2831c0f65a33
md"""
# The study at a glance

What was simulated, with which design, and what the engine concluded.

This notebook belongs to the study in this repository: it loads the artefacts the
pipeline produced (`data/analysis.json` and `reports/figures/*.png`), shows the
section of the report it is about, and prints that section to PDF in its last
cell. Nothing here is a copy of a number typed by hand -- every value comes from
the bundle, and the bundle comes from `scripts/run_study.jl`.
"""

# ╔═╡ da77243c-6b65-4909-ba51-77371000bfb5
md"""
## The environment

The first cell activates `notebooks/Project.toml`, which has `DiscreteSim` (this
repository, developed in place) together with `PlutoUI` and `Plots`. Activating it
explicitly means the notebook runs the same environment interactively and headless
(`scripts/run_notebooks.jl`), with no package installation in the middle.
"""

# ╔═╡ 7bb8477a-6e52-4cd7-8ed5-92c49ec5da98
begin
ROOT = dirname(@__DIR__)
end

# ╔═╡ c58affdc-1965-45fa-8ca8-1fd1ecb9b08e
md"""
## The study, loaded from disk

`load_study` reads the JSON the pipeline wrote and turns it back into the
symbol-keyed records the package uses, so the notebook and the printed report
show the same numbers without re-running the study.
"""

# ╔═╡ a5e90385-6eae-4292-b946-3c3aabcc9725
begin
bundle = load_study(ROOT);
end

# ╔═╡ 018d13aa-0b73-4dd9-88c0-b0215c4f91e9
begin
TableOfContents()
end

# ╔═╡ 92d73b34-db78-4c88-9521-1d2574f72731
md"""
## The section: *Overview*
"""

# ╔═╡ 5f169717-75b3-4eaa-8903-c293274a267d
begin
HTML(preview_section(bundle, :overview))
end

# ╔═╡ 46d21d95-5495-4bac-95b2-c887a97c81e7
md"""
## What the study produced

The manifest is the pipeline's own summary: the design, the verdicts and the
number of artefacts. It is what a scheduled job looks at.
"""

# ╔═╡ e218525e-98da-438c-84ec-5b808db06d51
begin
bundle[:manifest]
end

# ╔═╡ 88b4cac7-54b9-4346-a253-c36608111eff
begin
bundle[:config]
end

# ╔═╡ cd6ca46b-3b6b-40d3-876c-2d02d0e18861
md"""
## The five models

Every model of the package answers one question, and they all record the same
kind of statistics -- which is why one report can print all of them.
"""

# ╔═╡ 5c3acbbf-2a03-4238-a537-75bf34ca134d
begin
rows = [SymDict(:model => name, :title => catalogue(name).title,
            :entity => catalogue(name).entity, :theory => catalogue(name).theory,
            :params => join(code_string.(catalogue(name).params), ", "))
        for name in MODELS]
    table_html(rows, [:model, :title, :entity, :theory]) |> HTML
end

# ╔═╡ 081fca94-83dc-4786-8e5c-ae15064a4f0b
md"""
## The printout, and its PDF

The cell below writes the section as a self-contained HTML printout and prints it
with a headless browser: `reports/html/notebook_overview.html` and
`reports/pdf/notebook_overview.pdf`. The notebook *is* the report -- the PDF is its
printout.
"""

# ╔═╡ a3f4b81d-3b03-4dd6-b86b-34c2595314db
begin
println("run the study first if this file is missing: julia --project=. scripts/run_study.jl")
    print_section_pdf(bundle, :overview; root = ROOT)
end

# ╔═╡ 72841ee2-f84d-4399-b461-66a19cafc483
md"""
---
*Generated by `DiscreteSim.jl` from `data/analysis.json` (seed
`$(get(get(bundle, :config, SymDict()), :seed, 0))`). Re-run
`julia --project=. scripts/run_study.jl` to refresh every number in this notebook.*
"""

# ╔═╡ Cell order:
# ╠═19b5fdb4-5c36-4761-a2ed-2831c0f65a33
# ╠═da77243c-6b65-4909-ba51-77371000bfb5
# ╠═859724e0-09cd-48e1-9f82-bb91cb1ac913
# ╠═6ebac3b2-1c48-4e4b-bc10-1e180a81a824
# ╠═7bb8477a-6e52-4cd7-8ed5-92c49ec5da98
# ╠═c58affdc-1965-45fa-8ca8-1fd1ecb9b08e
# ╠═a5e90385-6eae-4292-b946-3c3aabcc9725
# ╠═018d13aa-0b73-4dd9-88c0-b0215c4f91e9
# ╠═92d73b34-db78-4c88-9521-1d2574f72731
# ╠═5f169717-75b3-4eaa-8903-c293274a267d
# ╠═46d21d95-5495-4bac-95b2-c887a97c81e7
# ╠═e218525e-98da-438c-84ec-5b808db06d51
# ╠═88b4cac7-54b9-4346-a253-c36608111eff
# ╠═cd6ca46b-3b6b-40d3-876c-2d02d0e18861
# ╠═5c3acbbf-2a03-4238-a537-75bf34ca134d
# ╠═081fca94-83dc-4786-8e5c-ae15064a4f0b
# ╠═a3f4b81d-3b03-4dd6-b86b-34c2595314db
# ╠═72841ee2-f84d-4399-b461-66a19cafc483
