### A Pluto.jl notebook ###
# v1.0.3

using Markdown
using InteractiveUtils

# ╔═╡ 0885835e-e8ab-4ef5-9101-38de220fdce9
begin
import Pkg
    Pkg.activate(@__DIR__)
end

# ╔═╡ 3e470ae3-52e9-4210-ba42-9642ae9abd70
begin
using DiscreteSim
    using PlutoUI
    using Plots
    using Statistics
    using Printf
    using Dates
end

# ╔═╡ 1400c3e9-892c-415c-af41-1046c68310b6
md"""
# The study at a glance

What was simulated, with which design, and what the engine concluded.

This notebook belongs to the study in this repository: it loads the artefacts the
pipeline produced (`data/analysis.json` and `reports/figures/*.png`), shows the
section of the report it is about, and prints that section to PDF in its last
cell. Nothing here is a copy of a number typed by hand -- every value comes from
the bundle, and the bundle comes from `scripts/run_study.jl`.
"""

# ╔═╡ 6c519609-1456-4680-8d5f-692b3c460240
md"""
## The environment

The first cell activates `notebooks/Project.toml`, which has `DiscreteSim` (this
repository, developed in place) together with `PlutoUI` and `Plots`. Activating it
explicitly means the notebook runs the same environment interactively and headless
(`scripts/run_notebooks.jl`), with no package installation in the middle.
"""

# ╔═╡ e7f26d14-7171-4b2c-b6f2-6a8f0c32d2fd
begin
ROOT = dirname(@__DIR__)
end

# ╔═╡ f3ad7949-886c-4350-9288-0a4bcd14792a
md"""
## The study, loaded from disk

`load_study` reads the JSON the pipeline wrote and turns it back into the
symbol-keyed records the package uses, so the notebook and the printed report
show the same numbers without re-running the study.
"""

# ╔═╡ 136876c9-218b-409e-b2b4-7ea632f30a80
begin
bundle = load_study(ROOT);
end

# ╔═╡ 9fb756e1-1a7f-4e57-a2bd-c0eb5577132e
begin
TableOfContents()
end

# ╔═╡ 390edf15-792a-4140-9d8b-26540ee0ecc1
md"""
## The section: *Overview*
"""

# ╔═╡ ff9d13cd-9015-4627-b5a5-3f84677deff3
begin
HTML(preview_section(bundle, :overview))
end

# ╔═╡ 03747917-1d86-4094-b6a8-5b08e7b3e419
md"""
## What the study produced

The manifest is the pipeline's own summary: the design, the verdicts and the
number of artefacts. It is what a scheduled job looks at.
"""

# ╔═╡ bbb56229-0e4d-410c-b08a-14e7dbf07b6a
begin
bundle[:manifest]
end

# ╔═╡ 88d25efe-77e2-41bb-9171-47ca8c476c80
begin
bundle[:config]
end

# ╔═╡ 1c954905-a15d-4c3f-8073-e70aa2c85660
md"""
## The five models

Every model of the package answers one question, and they all record the same
kind of statistics -- which is why one report can print all of them.
"""

# ╔═╡ 75b77942-2db2-4427-aceb-2cbfbe568db8
begin
rows = [SymDict(:model => name, :title => catalogue(name).title,
            :entity => catalogue(name).entity, :theory => catalogue(name).theory,
            :params => join(code_string.(catalogue(name).params), ", "))
        for name in MODELS]
    table_html(rows, [:model, :title, :entity, :theory]) |> HTML
end

# ╔═╡ e6d10b68-41df-464c-ab8b-fa118f1c887f
md"""
## The printout, and its PDF

The cell below writes the section as a self-contained HTML printout and prints it
with a headless browser: `reports/html/notebook_overview.html` and
`reports/pdf/notebook_overview.pdf`. The notebook *is* the report -- the PDF is its
printout.
"""

# ╔═╡ 17b8653d-ea7a-4ec9-b04f-2bc23f4d9a92
begin
println("run the study first if this file is missing: julia --project=. scripts/run_study.jl")
    print_section_pdf(bundle, :overview; root = ROOT)
end

# ╔═╡ 9982f9b4-4f6c-4ce7-bf87-702802f288f0
md"""
---
*Generated by `DiscreteSim.jl` from `data/analysis.json` (seed
`$(get(get(bundle, :config, SymDict()), :seed, 0))`). Re-run
`julia --project=. scripts/run_study.jl` to refresh every number in this notebook.*
"""

# ╔═╡ Cell order:
# ╠═1400c3e9-892c-415c-af41-1046c68310b6
# ╠═6c519609-1456-4680-8d5f-692b3c460240
# ╠═0885835e-e8ab-4ef5-9101-38de220fdce9
# ╠═3e470ae3-52e9-4210-ba42-9642ae9abd70
# ╠═e7f26d14-7171-4b2c-b6f2-6a8f0c32d2fd
# ╠═f3ad7949-886c-4350-9288-0a4bcd14792a
# ╠═136876c9-218b-409e-b2b4-7ea632f30a80
# ╠═9fb756e1-1a7f-4e57-a2bd-c0eb5577132e
# ╠═390edf15-792a-4140-9d8b-26540ee0ecc1
# ╠═ff9d13cd-9015-4627-b5a5-3f84677deff3
# ╠═03747917-1d86-4094-b6a8-5b08e7b3e419
# ╠═bbb56229-0e4d-410c-b08a-14e7dbf07b6a
# ╠═88d25efe-77e2-41bb-9171-47ca8c476c80
# ╠═1c954905-a15d-4c3f-8073-e70aa2c85660
# ╠═75b77942-2db2-4427-aceb-2cbfbe568db8
# ╠═e6d10b68-41df-464c-ab8b-fa118f1c887f
# ╠═17b8653d-ea7a-4ec9-b04f-2bc23f4d9a92
# ╠═9982f9b4-4f6c-4ce7-bf87-702802f288f0
