### A Pluto.jl notebook ###
# v0.20.23

using Markdown
using InteractiveUtils

# This Pluto notebook uses @bind for interactivity. When running this notebook outside of Pluto, the following 'mock version' of @bind gives bound variables a default value (instead of an error).
macro bind(def, element)
    quote
        local iv = try Base.loaded_modules[Base.PkgId(Base.UUID("6e696c72-6542-2067-7265-42206c756150"), "AbstractPlutoDingetjes")].Bonds.initial_value catch; b -> missing; end
        local el = $(esc(element))
        global $(esc(def)) = Core.applicable(Base.get, el) ? Base.get(el) : iv(el)
        el
    end
end

# ╔═╡ 6a2d152f-8059-44f6-a12c-ba315f8de93b
md"""
# The study at a glance

What was simulated, with which design, and what the engine concluded.

This notebook belongs to the study in this repository: it loads the artefacts the
pipeline produced (`data/analysis.json` and `reports/figures/*.png`), shows the
section of the report it is about, and prints that section to PDF in its last
cell. Nothing here is a copy of a number typed by hand -- every value comes from
the bundle, and the bundle comes from `scripts/run_study.jl`.
"""

# ╔═╡ d33121bf-2ba2-4c71-9cb5-3d2d7589e401
md"""
## The environment

The first cell activates `notebooks/Project.toml`, which has `DiscreteSim` (this
repository, developed in place) together with `PlutoUI` and `Plots`. Activating it
explicitly means the notebook runs the same environment interactively and headless
(`scripts/run_notebooks.jl`), with no package installation in the middle.
"""

# ╔═╡ 469be70d-0fdb-4f1a-b376-241b67d33d89
begin
import Pkg
    Pkg.activate(@__DIR__)
end

# ╔═╡ 3db7cec7-a1d0-4247-bc23-11e6b12c9840
begin
using DiscreteSim
    using PlutoUI
    using Plots
    using Statistics
    using Printf
    using Dates
end

# ╔═╡ e6a15e02-53e4-41f9-b873-ef27bd327068
begin
ROOT = dirname(@__DIR__)
end

# ╔═╡ 013f8c58-9282-46bc-9a68-d25cdcdf94e1
md"""
## The study, loaded from disk

`load_study` reads the JSON the pipeline wrote and turns it back into the
symbol-keyed records the package uses, so the notebook and the printed report
show the same numbers without re-running the study.
"""

# ╔═╡ 40f36057-6b81-4c14-8727-bae2da227906
begin
bundle = load_study(ROOT);
end

# ╔═╡ 920449d1-d726-4a09-af2e-38e5f821b835
begin
TableOfContents()
end

# ╔═╡ 9532503c-0806-4320-b4ac-68bed450b72d
md"""
## The section: *Overview*
"""

# ╔═╡ 805a8a39-d2ca-4d5d-97cb-b407d3aa8f0a
begin
HTML(preview_section(bundle, :overview))
end

# ╔═╡ a3a0b15d-4b59-4e54-8f26-9f898d1ed79e
md"""
## What the study produced

The manifest is the pipeline's own summary: the design, the verdicts and the
number of artefacts. It is what a scheduled job looks at.
"""

# ╔═╡ 60fdae6d-94c9-4d66-a2ea-e056a996d234
begin
bundle[:manifest]
end

# ╔═╡ 2aa0d971-c9ee-4b05-8dc7-aca05f32fd7c
begin
bundle[:config]
end

# ╔═╡ 08575840-7839-4d2d-a8dc-f3079bd24c37
md"""
## The five models

Every model of the package answers one question, and they all record the same
kind of statistics -- which is why one report can print all of them.
"""

# ╔═╡ 369be674-d8c9-4976-b814-be169feaf01b
begin
rows = [SymDict(:model => name, :title => catalogue(name).title,
            :entity => catalogue(name).entity, :theory => catalogue(name).theory,
            :params => join(code_string.(catalogue(name).params), ", "))
        for name in MODELS]
    table_html(rows, [:model, :title, :entity, :theory]) |> HTML
end

# ╔═╡ 1942d1fd-787b-4eec-9403-49c9fa4beb3a
md"""
## The printout, and its PDF

The cell below writes the section as a self-contained HTML printout and prints it
with a headless browser: `reports/html/notebook_overview.html` and
`reports/pdf/notebook_overview.pdf`. The notebook *is* the report -- the PDF is its
printout.
"""

# ╔═╡ 6a0a1cbd-afbe-420f-9e13-57976da2da51
begin
println("run the study first if this file is missing: julia --project=. scripts/run_study.jl")
    print_section_pdf(bundle, :overview; root = ROOT)
end

# ╔═╡ e68849a6-2015-47aa-a2af-2947d19214b2
md"""
---
*Generated by `DiscreteSim.jl` from `data/analysis.json` (seed
`$(get(get(bundle, :config, SymDict()), :seed, 0))`). Re-run
`julia --project=. scripts/run_study.jl` to refresh every number in this notebook.*
"""

# ╔═╡ Cell order:
# ╠═6a2d152f-8059-44f6-a12c-ba315f8de93b
# ╠═d33121bf-2ba2-4c71-9cb5-3d2d7589e401
# ╠═469be70d-0fdb-4f1a-b376-241b67d33d89
# ╠═3db7cec7-a1d0-4247-bc23-11e6b12c9840
# ╠═e6a15e02-53e4-41f9-b873-ef27bd327068
# ╠═013f8c58-9282-46bc-9a68-d25cdcdf94e1
# ╠═40f36057-6b81-4c14-8727-bae2da227906
# ╠═920449d1-d726-4a09-af2e-38e5f821b835
# ╠═9532503c-0806-4320-b4ac-68bed450b72d
# ╠═805a8a39-d2ca-4d5d-97cb-b407d3aa8f0a
# ╠═a3a0b15d-4b59-4e54-8f26-9f898d1ed79e
# ╠═60fdae6d-94c9-4d66-a2ea-e056a996d234
# ╠═2aa0d971-c9ee-4b05-8dc7-aca05f32fd7c
# ╠═08575840-7839-4d2d-a8dc-f3079bd24c37
# ╠═369be674-d8c9-4976-b814-be169feaf01b
# ╠═1942d1fd-787b-4eec-9403-49c9fa4beb3a
# ╠═6a0a1cbd-afbe-420f-9e13-57976da2da51
# ╠═e68849a6-2015-47aa-a2af-2947d19214b2
