### A Pluto.jl notebook ###
# v1.0.3

using Markdown
using InteractiveUtils

# This Pluto notebook uses @bind for interactivity. When running this notebook outside of Pluto, the following 'mock version' of @bind gives bound variables a default value (instead of an error).
macro bind(def, element)
    #! format: off
    return quote
        local iv = try Base.loaded_modules[Base.PkgId(Base.UUID("6e696c72-6542-2067-7265-42206c756150"), "AbstractPlutoDingetjes")].Bonds.initial_value catch; b -> missing; end
        local el = $(esc(element))
        global $(esc(def)) = Core.applicable(Base.get, el) ? Base.get(el) : iv(el)
        el
    end
    #! format: on
end

# ╔═╡ 7d97dc61-6ee2-447e-b292-f9e124347216
begin
import Pkg
    Pkg.activate(@__DIR__)
end

# ╔═╡ d1f6120c-5278-4147-b9e3-55a91f03e6ec
begin
using DiscreteSim
    using PlutoUI
    using Plots
    using Statistics
    using Printf
    using Dates
end

# ╔═╡ eea59707-7100-474a-a478-7a38f6ffac30
md"""
# The five models

A service pool, a transfer line, a job shop, an inventory position and a contact centre, all on one engine.

This notebook belongs to the study in this repository: it loads the artefacts the
pipeline produced (`data/analysis.json` and `reports/figures/*.png`), shows the
section of the report it is about, and prints that section to PDF in its last
cell. Nothing here is a copy of a number typed by hand -- every value comes from
the bundle, and the bundle comes from `scripts/run_study.jl`.
"""

# ╔═╡ ef6d828d-608d-4742-ae41-84d6b2323aa5
md"""
## The environment

The first cell activates `notebooks/Project.toml`, which has `DiscreteSim` (this
repository, developed in place) together with `PlutoUI` and `Plots`. Activating it
explicitly means the notebook runs the same environment interactively and headless
(`scripts/run_notebooks.jl`), with no package installation in the middle.
"""

# ╔═╡ 0b46a319-c2e5-40db-917e-92881a5e5324
begin
ROOT = dirname(@__DIR__)
end

# ╔═╡ c3ab9155-92bd-4659-ae50-a84095f49f83
md"""
## The study, loaded from disk

`load_study` reads the JSON the pipeline wrote and turns it back into the
symbol-keyed records the package uses, so the notebook and the printed report
show the same numbers without re-running the study.
"""

# ╔═╡ c08ed79a-96bd-4d22-a059-7fb2a91fe38d
begin
bundle = load_study(ROOT);
end

# ╔═╡ 2cd33bd7-a912-4465-a71a-3388135cef4c
begin
TableOfContents()
end

# ╔═╡ b58c6960-3682-4cbd-8935-63cdd0df151b
md"""
## The section: *Models*
"""

# ╔═╡ ae8cd5f2-c94d-49c2-9d19-87b7c013634e
begin
HTML(preview_section(bundle, :models))
end

# ╔═╡ 3c90cecc-9716-462c-ae27-7788643b79bf
md"""
## Every model, one at a time

Pick a model, build it from its **calibrated** parameters (the ones the data layer
produced) and run it: the metrics come from the engine, and the last row is the
cross-check — Erlang C for the queues, Little's law for the rest.
"""

# ╔═╡ a6fa50ae-b398-44d0-90ab-1fd586552924
begin
@bind choice Select([code_string(m) => m for m in MODELS]; default = :machine_shop)
end

# ╔═╡ 7931b2ca-1337-4501-a2fc-a2dde4c8184e
begin
chosen = model_params_from_calibration(bundle[:calibration], choice)
    sample = build_model(choice, chosen,
        SymDict(:seed => get(bundle[:config], :seed, 20260101), :horizon => 4000.0,
            :warmup => 400.0, :trace => true))
    run!(sample);
    servers = [r for (_, r) in sample.resources if r isa DiscreteSim.Resource]
    SymDict(:model => choice, :validation => validate_model(sample, choice, chosen)[:verdict],
        :completed => count_of(sample[:completed]),
        :mean_utilisation => round(sum(utilisation(r) for r in servers) /
            max(length(servers), 1), digits = 3))
end

# ╔═╡ 83cf8e22-5000-42e2-a3b7-b4a0b33801e7
begin
rows = [SymDict(:metric => get(r, :name, :unknown), :kind => get(r, :kind, :unknown),
            :mean => get(r, :mean, NaN), :unit => get(r, :unit, :count))
            for r in statistics_table(sample)]
    table_html(rows, [:metric, :kind, :mean, :unit]) |> HTML
end

# ╔═╡ 80efe0c9-f60a-47a7-8b60-c8f082fab089
begin
fig_utilisation(sample)
end

# ╔═╡ 240355b6-3630-4a5d-a1d7-e3a20364d1d2
begin
from_study = metric_ci(bundle[:models][choice], :throughput)
    (choice = choice, source = :from_the_study,
        throughput = from_study === nothing ? NaN : from_study[:mean])
end

# ╔═╡ ba06b046-9369-4083-9e18-80a4368e9c82
md"""
## The printout, and its PDF

The cell below writes the section as a self-contained HTML printout and prints it
with a headless browser: `reports/html/notebook_models.html` and
`reports/pdf/notebook_models.pdf`. The notebook *is* the report -- the PDF is its
printout.
"""

# ╔═╡ 215807b8-df6a-4f18-a16c-32e3fb05d37a
begin
println("run the study first if this file is missing: julia --project=. scripts/run_study.jl")
    print_section_pdf(bundle, :models; root = ROOT)
end

# ╔═╡ ac3d8134-3315-460c-b47a-adefd157a34d
md"""
---
*Generated by `DiscreteSim.jl` from `data/analysis.json` (seed
`$(get(get(bundle, :config, SymDict()), :seed, 0))`). Re-run
`julia --project=. scripts/run_study.jl` to refresh every number in this notebook.*
"""

# ╔═╡ Cell order:
# ╠═eea59707-7100-474a-a478-7a38f6ffac30
# ╠═ef6d828d-608d-4742-ae41-84d6b2323aa5
# ╠═7d97dc61-6ee2-447e-b292-f9e124347216
# ╠═d1f6120c-5278-4147-b9e3-55a91f03e6ec
# ╠═0b46a319-c2e5-40db-917e-92881a5e5324
# ╠═c3ab9155-92bd-4659-ae50-a84095f49f83
# ╠═c08ed79a-96bd-4d22-a059-7fb2a91fe38d
# ╠═2cd33bd7-a912-4465-a71a-3388135cef4c
# ╠═b58c6960-3682-4cbd-8935-63cdd0df151b
# ╠═ae8cd5f2-c94d-49c2-9d19-87b7c013634e
# ╠═3c90cecc-9716-462c-ae27-7788643b79bf
# ╠═a6fa50ae-b398-44d0-90ab-1fd586552924
# ╠═7931b2ca-1337-4501-a2fc-a2dde4c8184e
# ╠═83cf8e22-5000-42e2-a3b7-b4a0b33801e7
# ╠═80efe0c9-f60a-47a7-8b60-c8f082fab089
# ╠═240355b6-3630-4a5d-a1d7-e3a20364d1d2
# ╠═ba06b046-9369-4083-9e18-80a4368e9c82
# ╠═215807b8-df6a-4f18-a16c-32e3fb05d37a
# ╠═ac3d8134-3315-460c-b47a-adefd157a34d
