### A Pluto.jl notebook ###
# v0.20.23

using Markdown
using InteractiveUtils

# This Pluto notebook uses @bind for interactivity. When running this notebook outside of Pluto, the following 'mock version' of @bind gives bound variables a default value (instead of an error).
macro bind(def, element)
    quote
        local iv = try Base.loaded_modules[Base.PkgId(Base.UUID("6e696c72-6542-2067-7265-42206c756150"), "AbstractPlutoDingetjes")].Bonds.initial_value catch; b -> missing; end
        local el = $(esc(element))
        global $(esc(def)) = Core.applicable(Base.get, el) ? Base.get(el) : iv(el)
        el
    end
end

# ╔═╡ dab74212-5e01-456f-9de2-0464418de0e8
md"""
# The five models

A service pool, a transfer line, a job shop, an inventory position and a contact centre, all on one engine.

This notebook belongs to the study in this repository: it loads the artefacts the
pipeline produced (`data/analysis.json` and `reports/figures/*.png`), shows the
section of the report it is about, and prints that section to PDF in its last
cell. Nothing here is a copy of a number typed by hand -- every value comes from
the bundle, and the bundle comes from `scripts/run_study.jl`.
"""

# ╔═╡ 617adf5a-5754-4673-ad1b-354c81a517f9
md"""
## The environment

The first cell activates `notebooks/Project.toml`, which has `DiscreteSim` (this
repository, developed in place) together with `PlutoUI` and `Plots`. Activating it
explicitly means the notebook runs the same environment interactively and headless
(`scripts/run_notebooks.jl`), with no package installation in the middle.
"""

# ╔═╡ 34e194bb-f775-4b55-8054-9e932b643f77
begin
import Pkg
    Pkg.activate(@__DIR__)
end

# ╔═╡ 059ce9d0-f4ed-4b6e-98c5-5bc394cd89fe
begin
using DiscreteSim
    using PlutoUI
    using Plots
    using Statistics
    using Printf
    using Dates
end

# ╔═╡ bc535944-8b51-41b8-8e52-080fa356e431
begin
ROOT = dirname(@__DIR__)
end

# ╔═╡ d5fa439a-c473-4e6c-8d1c-61c5f8842f18
md"""
## The study, loaded from disk

`load_study` reads the JSON the pipeline wrote and turns it back into the
symbol-keyed records the package uses, so the notebook and the printed report
show the same numbers without re-running the study.
"""

# ╔═╡ 629ebb5f-f35d-44ce-8942-186fc69fd336
begin
bundle = load_study(ROOT);
end

# ╔═╡ 1be524a7-fb5c-431d-b131-5083b6c2a5a3
begin
TableOfContents()
end

# ╔═╡ fb1edf77-d5af-4666-b0bf-12e182828d7e
md"""
## The section: *Models*
"""

# ╔═╡ 86ec5e08-a71a-4724-85b4-d2f7ca6570f9
begin
HTML(preview_section(bundle, :models))
end

# ╔═╡ 293b9621-c967-4c1f-a78f-e15556da621c
md"""
## Every model, one at a time

Pick a model, build it from its **calibrated** parameters (the ones the data layer
produced) and run it: the metrics come from the engine, and the last row is the
cross-check — Erlang C for the queues, Little's law for the rest.
"""

# ╔═╡ b8e9cea6-0b38-4783-a30f-51ed21b31b40
begin
@bind choice Select([code_string(m) => m for m in MODELS]; default = :machine_shop)
end

# ╔═╡ c05b25bd-1a03-4a13-9a9d-5a04b3a1907d
begin
chosen = model_params_from_calibration(bundle[:calibration], choice)
    sample = build_model(choice, chosen,
        SymDict(:seed => get(bundle[:config], :seed, 20260101), :horizon => 4000.0,
            :warmup => 400.0, :trace => true))
    run!(sample);
    servers = [r for (_, r) in sample.resources if r isa DiscreteSim.Resource]
    SymDict(:model => choice, :validation => validate_model(sample, choice, chosen)[:verdict],
        :completed => count_of(sample[:completed]),
        :mean_utilisation => round(sum(utilisation(r) for r in servers) /
            max(length(servers), 1), digits = 3))
end

# ╔═╡ f27df398-8690-4b94-a3e4-6bb97caaff9c
begin
rows = [SymDict(:metric => get(r, :name, :unknown), :kind => get(r, :kind, :unknown),
            :mean => get(r, :mean, NaN), :unit => get(r, :unit, :count))
            for r in statistics_table(sample)]
    table_html(rows, [:metric, :kind, :mean, :unit]) |> HTML
end

# ╔═╡ 0ab500c1-76b3-4e1e-ba03-c3ec22a73f44
begin
fig_utilisation(sample)
end

# ╔═╡ 9d5ec269-eef5-44c8-82b4-ac050011e9f7
begin
from_study = metric_ci(bundle[:models][choice], :throughput)
    (choice = choice, source = :from_the_study,
        throughput = from_study === nothing ? NaN : from_study[:mean])
end

# ╔═╡ 277a03ff-512f-4522-a57a-3fefaf9724b5
md"""
## The printout, and its PDF

The cell below writes the section as a self-contained HTML printout and prints it
with a headless browser: `reports/html/notebook_models.html` and
`reports/pdf/notebook_models.pdf`. The notebook *is* the report -- the PDF is its
printout.
"""

# ╔═╡ c679c8f4-3372-4bd2-875b-80bb199b189e
begin
println("run the study first if this file is missing: julia --project=. scripts/run_study.jl")
    print_section_pdf(bundle, :models; root = ROOT)
end

# ╔═╡ 27a9a355-34e2-43d3-b7a8-91f69e963e30
md"""
---
*Generated by `DiscreteSim.jl` from `data/analysis.json` (seed
`$(get(get(bundle, :config, SymDict()), :seed, 0))`). Re-run
`julia --project=. scripts/run_study.jl` to refresh every number in this notebook.*
"""

# ╔═╡ Cell order:
# ╠═dab74212-5e01-456f-9de2-0464418de0e8
# ╠═617adf5a-5754-4673-ad1b-354c81a517f9
# ╠═34e194bb-f775-4b55-8054-9e932b643f77
# ╠═059ce9d0-f4ed-4b6e-98c5-5bc394cd89fe
# ╠═bc535944-8b51-41b8-8e52-080fa356e431
# ╠═d5fa439a-c473-4e6c-8d1c-61c5f8842f18
# ╠═629ebb5f-f35d-44ce-8942-186fc69fd336
# ╠═1be524a7-fb5c-431d-b131-5083b6c2a5a3
# ╠═fb1edf77-d5af-4666-b0bf-12e182828d7e
# ╠═86ec5e08-a71a-4724-85b4-d2f7ca6570f9
# ╠═293b9621-c967-4c1f-a78f-e15556da621c
# ╠═b8e9cea6-0b38-4783-a30f-51ed21b31b40
# ╠═c05b25bd-1a03-4a13-9a9d-5a04b3a1907d
# ╠═f27df398-8690-4b94-a3e4-6bb97caaff9c
# ╠═0ab500c1-76b3-4e1e-ba03-c3ec22a73f44
# ╠═9d5ec269-eef5-44c8-82b4-ac050011e9f7
# ╠═277a03ff-512f-4522-a57a-3fefaf9724b5
# ╠═c679c8f4-3372-4bd2-875b-80bb199b189e
# ╠═27a9a355-34e2-43d3-b7a8-91f69e963e30
