### A Pluto.jl notebook ###
# v1.0.3

using Markdown
using InteractiveUtils

# ╔═╡ b19b9c00-3853-43d2-80ed-f2074ed53ce8
begin
import Pkg
    Pkg.activate(@__DIR__)
end

# ╔═╡ a1284c07-fb62-4ed5-bf5e-ea2985f743da
begin
using DiscreteSim
    using PlutoUI
    using Plots
    using Statistics
    using Printf
    using Dates
end

# ╔═╡ 01b07a1d-758a-48dd-85ed-a04740f0a209
md"""
# Calibration from plant data

Where the numbers in the model come from, and how well they fit.

This notebook belongs to the study in this repository: it loads the artefacts the
pipeline produced (`data/analysis.json` and `reports/figures/*.png`), shows the
section of the report it is about, and prints that section to PDF in its last
cell. Nothing here is a copy of a number typed by hand -- every value comes from
the bundle, and the bundle comes from `scripts/run_study.jl`.
"""

# ╔═╡ 44d80686-709a-4075-89c0-0d40d87a08d3
md"""
## The environment

The first cell activates `notebooks/Project.toml`, which has `DiscreteSim` (this
repository, developed in place) together with `PlutoUI` and `Plots`. Activating it
explicitly means the notebook runs the same environment interactively and headless
(`scripts/run_notebooks.jl`), with no package installation in the middle.
"""

# ╔═╡ 6b410df3-1972-4c23-aa66-65ef0c4e1074
begin
ROOT = dirname(@__DIR__)
end

# ╔═╡ 47ef3a72-7b7d-41f5-8b44-7ca90697676f
md"""
## The study, loaded from disk

`load_study` reads the JSON the pipeline wrote and turns it back into the
symbol-keyed records the package uses, so the notebook and the printed report
show the same numbers without re-running the study.
"""

# ╔═╡ a34321ec-abb2-46d1-a555-2e8d84355c35
begin
bundle = load_study(ROOT);
end

# ╔═╡ daeb8f80-15bd-450b-ba5d-fb4a50cbd783
begin
TableOfContents()
end

# ╔═╡ 4b3ae60e-d456-472e-b5bf-22bcd53cbe31
md"""
## The section: *Calibration*
"""

# ╔═╡ 83179857-6f0d-4677-851a-f02b4b30c01d
begin
HTML(preview_section(bundle, :calibration))
end

# ╔═╡ 634a4ad9-cb63-4673-a9f9-e8b992480482
md"""
## Fitting by hand

The pipeline fitted every series of the plant history. Here is the same work done
in the open: take a sample, fit four families by maximum likelihood, and let the
Kolmogorov--Smirnov statistic decide which one can be defended.
"""

# ╔═╡ 2f549067-fcd5-4c61-994b-468cc4d605f9
begin
truth = SymDict(:mean => 3.0, :shape => 4.0)
    γ_sample = let σ = Sim(:fit_demo; seed = 20260101)
        sample_n(σ, :demo, :gamma => (truth[:shape], truth[:mean] / truth[:shape]), 400)
    end
    best_fit(γ_sample; kinds = (:exponential, :lognormal, :gamma, :weibull))[:kind]
end

# ╔═╡ c760f11b-59e5-45d5-9511-54449fd86e97
begin
fitted = best_fit(γ_sample)
    table_html([SymDict(:family => k, :rank => rank[:rank], :ks_stat => rank[:ks_stat],
            :ks_p => rank[:ks_p], :aic => rank[:aic]) for (k, rank) in fitted[:ranking]],
        [:family, :rank, :ks_stat, :ks_p, :aic]) |> HTML
end

# ╔═╡ f3e3d188-9323-4f31-a6f1-edda27680f06
begin
fig_calibration(γ_sample, fitted; series = :demo)
end

# ╔═╡ fff0a76f-3bd4-4e7d-83df-56d73af5ff39
md"""
## How uncertain is a parameter?

The bootstrap resamples the observations, refits and reports the percentiles: that
is the interval a calibration report quotes for every fitted parameter.
"""

# ╔═╡ 6524b302-27d5-4623-b8fa-96a1ae9eaef5
begin
interval = bootstrap_ci(γ_sample, fitted[:kind], 1; reps = 80)
    SymDict(:family => fitted[:kind], :parameter => fitted[:params][1],
        :median => interval[:median], :lo => interval[:lo], :hi => interval[:hi])
end

# ╔═╡ 579fe2e4-46df-4bd8-9e6e-30f040111885
md"""
## What the plant data says about the model

`calibrate` does all of the above for every measured series, and
`model_params_from_calibration` turns the result into model parameters -- the ones
the pipeline then simulated.
"""

# ╔═╡ 8eccb938-15d2-4bce-8010-b8d6ef76e744
begin
from_data = bundle[:calibration][:parameters]
    SymDict(:arrival_rate => get(from_data, :arrival_rate, NaN),
        :service_rate => get(from_data, :service_rate, NaN),
        :mtbf => get(from_data, :mtbf, NaN), :mttr => get(from_data, :mttr, NaN),
        :availability => get(from_data, :availability, NaN))
end

# ╔═╡ 4dc2964c-1989-483e-8130-07db79ad3a5c
begin
bundle[:history][:summary]
end

# ╔═╡ 5f392b61-c221-4b87-895e-b00dd268d17d
md"""
## The printout, and its PDF

The cell below writes the section as a self-contained HTML printout and prints it
with a headless browser: `reports/html/notebook_calibration.html` and
`reports/pdf/notebook_calibration.pdf`. The notebook *is* the report -- the PDF is its
printout.
"""

# ╔═╡ bca1a5a6-46ba-4501-b9ff-26483f8774a8
begin
println("run the study first if this file is missing: julia --project=. scripts/run_study.jl")
    print_section_pdf(bundle, :calibration; root = ROOT)
end

# ╔═╡ 060ced20-a7d6-4025-accc-fefff488a1e8
begin
Markdown.parse(string("---\n",
        "*Generated by `DiscreteSim.jl` from `data/analysis.json` (seed `",
        get(get(bundle, :config, SymDict()), :seed, 0),
        "`). Re-run `julia --project=. scripts/run_study.jl` to refresh every number ",
        "in this notebook.*"))
end

# ╔═╡ Cell order:
# ╠═01b07a1d-758a-48dd-85ed-a04740f0a209
# ╠═44d80686-709a-4075-89c0-0d40d87a08d3
# ╠═b19b9c00-3853-43d2-80ed-f2074ed53ce8
# ╠═a1284c07-fb62-4ed5-bf5e-ea2985f743da
# ╠═6b410df3-1972-4c23-aa66-65ef0c4e1074
# ╠═47ef3a72-7b7d-41f5-8b44-7ca90697676f
# ╠═a34321ec-abb2-46d1-a555-2e8d84355c35
# ╠═daeb8f80-15bd-450b-ba5d-fb4a50cbd783
# ╠═4b3ae60e-d456-472e-b5bf-22bcd53cbe31
# ╠═83179857-6f0d-4677-851a-f02b4b30c01d
# ╠═634a4ad9-cb63-4673-a9f9-e8b992480482
# ╠═2f549067-fcd5-4c61-994b-468cc4d605f9
# ╠═c760f11b-59e5-45d5-9511-54449fd86e97
# ╠═f3e3d188-9323-4f31-a6f1-edda27680f06
# ╠═fff0a76f-3bd4-4e7d-83df-56d73af5ff39
# ╠═6524b302-27d5-4623-b8fa-96a1ae9eaef5
# ╠═579fe2e4-46df-4bd8-9e6e-30f040111885
# ╠═8eccb938-15d2-4bce-8010-b8d6ef76e744
# ╠═4dc2964c-1989-483e-8130-07db79ad3a5c
# ╠═5f392b61-c221-4b87-895e-b00dd268d17d
# ╠═bca1a5a6-46ba-4501-b9ff-26483f8774a8
# ╠═060ced20-a7d6-4025-accc-fefff488a1e8
