### A Pluto.jl notebook ###
# v0.20.23

using Markdown
using InteractiveUtils

# This Pluto notebook uses @bind for interactivity. When running this notebook outside of Pluto, the following 'mock version' of @bind gives bound variables a default value (instead of an error).
macro bind(def, element)
    quote
        local iv = try Base.loaded_modules[Base.PkgId(Base.UUID("6e696c72-6542-2067-7265-42206c756150"), "AbstractPlutoDingetjes")].Bonds.initial_value catch; b -> missing; end
        local el = $(esc(element))
        global $(esc(def)) = Core.applicable(Base.get, el) ? Base.get(el) : iv(el)
        el
    end
end

# ╔═╡ a033d95b-323f-42c9-aac4-a99f722fc6e3
md"""
# Artefacts and the printed report

Every file the study produced, and the one call that prints the whole report.

This notebook belongs to the study in this repository: it loads the artefacts the
pipeline produced (`data/analysis.json` and `reports/figures/*.png`), shows the
section of the report it is about, and prints that section to PDF in its last
cell. Nothing here is a copy of a number typed by hand -- every value comes from
the bundle, and the bundle comes from `scripts/run_study.jl`.
"""

# ╔═╡ 578e5e96-2606-4e6c-bcbc-33af5669c9fa
md"""
## The environment

The first cell activates `notebooks/Project.toml`, which has `DiscreteSim` (this
repository, developed in place) together with `PlutoUI` and `Plots`. Activating it
explicitly means the notebook runs the same environment interactively and headless
(`scripts/run_notebooks.jl`), with no package installation in the middle.
"""

# ╔═╡ 79ee894a-2561-49c5-a86e-44fae66289b8
begin
import Pkg
    Pkg.activate(@__DIR__)
end

# ╔═╡ 009cc3f7-ed35-45dc-84fd-1378ea674359
begin
using DiscreteSim
    using PlutoUI
    using Plots
    using Statistics
    using Printf
    using Dates
end

# ╔═╡ 3a06add0-bf68-405f-a02a-b54919b17e3b
begin
ROOT = dirname(@__DIR__)
end

# ╔═╡ 012b81a6-0f1d-4bd0-a155-5da61d0cd875
md"""
## The study, loaded from disk

`load_study` reads the JSON the pipeline wrote and turns it back into the
symbol-keyed records the package uses, so the notebook and the printed report
show the same numbers without re-running the study.
"""

# ╔═╡ 42df3de0-ecaa-41ff-a44a-0b1163fca883
begin
bundle = load_study(ROOT);
end

# ╔═╡ a5a26da4-7a2e-4851-ad72-addda3342420
begin
TableOfContents()
end

# ╔═╡ 6435d7fb-e38b-47c1-84c9-48b838e9366c
md"""
## The section: *Reports*
"""

# ╔═╡ ddbc95b3-84f9-4660-b2a1-7bf631d5891a
begin
HTML(preview_section(bundle, :reports))
end

# ╔═╡ 1783594f-a395-4d4a-88ae-f98a1a45306e
md"""
## Everything the study produced

The pipeline writes its numbers to `data/`, its figures to `reports/figures/`, its
printouts to `reports/html/` and its PDFs to `reports/pdf/`. The cell below lists
them with their size, so a reader can see what the study is made of.
"""

# ╔═╡ bbec7089-9cda-4c70-8677-e5156737a1ec
begin
file_rows = SymDict[]
    for kind in (:data, :figures, :html, :pdf)
        for p in get(bundle[:artifacts], kind, String[])
            path = joinpath(ROOT, String(p))
            isfile(path) || continue
            push!(file_rows, SymDict(:kind => kind, :file => relpath(path, ROOT),
                :bytes => filesize(path)))
        end
    end
    table_html(file_rows, [:kind, :file, :bytes]) |> HTML
end

# ╔═╡ 4385fade-99dc-4b1c-ae16-86490df17678
md"""
## The whole report, in one PDF

A single call prints every section of the study as one document -- the same HTML the
sections above show, in order, with a table of contents.
"""

# ╔═╡ d43fae6a-fda6-44c5-ab98-a5579b7ce0c5
begin
full = print_report_pdf(bundle; root = ROOT)
    SymDict(:html => relpath(full[:html], ROOT), :pdf => relpath(full[:pdf], ROOT),
        :printed => full[:printed], :pdf_bytes => get(full, :pdf_bytes, 0))
end

# ╔═╡ 8823f351-06dc-46ea-a262-9f52b89f0056
begin
capability = pdf_capability()
    SymDict(:available => capability[:available], :browser => get(capability, :browser, :none))
end

# ╔═╡ 89a7e712-a6fc-442a-aee9-7d0f50b2b39d
begin
manifest = bundle[:manifest]
    (kind = :manifest, entries = length(manifest), status = get(manifest, :status, :ok),
        n_pdf = get(manifest, :n_pdf, 0), elapsed_seconds = get(manifest, :elapsed_seconds, 0.0))
end

# ╔═╡ 6e916a21-4d27-43c4-8f10-146bea2b1fdf
md"""
## The printout, and its PDF

The cell below writes the section as a self-contained HTML printout and prints it
with a headless browser: `reports/html/notebook_reports.html` and
`reports/pdf/notebook_reports.pdf`. The notebook *is* the report -- the PDF is its
printout.
"""

# ╔═╡ 30196928-8904-4cb2-8f67-f780a64e75d1
begin
println("run the study first if this file is missing: julia --project=. scripts/run_study.jl")
    print_section_pdf(bundle, :reports; root = ROOT)
end

# ╔═╡ 0b6db4ae-0dc4-47c1-bec1-21eb307ab896
md"""
---
*Generated by `DiscreteSim.jl` from `data/analysis.json` (seed
`$(get(get(bundle, :config, SymDict()), :seed, 0))`). Re-run
`julia --project=. scripts/run_study.jl` to refresh every number in this notebook.*
"""

# ╔═╡ Cell order:
# ╠═a033d95b-323f-42c9-aac4-a99f722fc6e3
# ╠═578e5e96-2606-4e6c-bcbc-33af5669c9fa
# ╠═79ee894a-2561-49c5-a86e-44fae66289b8
# ╠═009cc3f7-ed35-45dc-84fd-1378ea674359
# ╠═3a06add0-bf68-405f-a02a-b54919b17e3b
# ╠═012b81a6-0f1d-4bd0-a155-5da61d0cd875
# ╠═42df3de0-ecaa-41ff-a44a-0b1163fca883
# ╠═a5a26da4-7a2e-4851-ad72-addda3342420
# ╠═6435d7fb-e38b-47c1-84c9-48b838e9366c
# ╠═ddbc95b3-84f9-4660-b2a1-7bf631d5891a
# ╠═1783594f-a395-4d4a-88ae-f98a1a45306e
# ╠═bbec7089-9cda-4c70-8677-e5156737a1ec
# ╠═4385fade-99dc-4b1c-ae16-86490df17678
# ╠═d43fae6a-fda6-44c5-ab98-a5579b7ce0c5
# ╠═8823f351-06dc-46ea-a262-9f52b89f0056
# ╠═89a7e712-a6fc-442a-aee9-7d0f50b2b39d
# ╠═6e916a21-4d27-43c4-8f10-146bea2b1fdf
# ╠═30196928-8904-4cb2-8f67-f780a64e75d1
# ╠═0b6db4ae-0dc4-47c1-bec1-21eb307ab896
