### A Pluto.jl notebook ###
# v0.20.23

using Markdown
using InteractiveUtils

# This Pluto notebook uses @bind for interactivity. When running this notebook outside of Pluto, the following 'mock version' of @bind gives bound variables a default value (instead of an error).
macro bind(def, element)
    quote
        local iv = try Base.loaded_modules[Base.PkgId(Base.UUID("6e696c72-6542-2067-7265-42206c756150"), "AbstractPlutoDingetjes")].Bonds.initial_value catch; b -> missing; end
        local el = $(esc(element))
        global $(esc(def)) = Core.applicable(Base.get, el) ? Base.get(el) : iv(el)
        el
    end
end

# ╔═╡ 0a9ee0fc-ac97-4abd-86f3-d477f5200e0c
md"""
# Artefacts and the printed report

Every file the study produced, and the one call that prints the whole report.

This notebook belongs to the study in this repository: it loads the artefacts the
pipeline produced (`data/analysis.json` and `reports/figures/*.png`), shows the
section of the report it is about, and prints that section to PDF in its last
cell. Nothing here is a copy of a number typed by hand -- every value comes from
the bundle, and the bundle comes from `scripts/run_study.jl`.
"""

# ╔═╡ 74ba452f-3981-4c78-b251-aa58907663b2
md"""
## The environment

The first cell activates `notebooks/Project.toml`, which has `DiscreteSim` (this
repository, developed in place) together with `PlutoUI` and `Plots`. Activating it
explicitly means the notebook runs the same environment interactively and headless
(`scripts/run_notebooks.jl`), with no package installation in the middle.
"""

# ╔═╡ 2ae2c8c0-19b7-4782-af2e-9abca3667242
begin
import Pkg
    Pkg.activate(@__DIR__)
end

# ╔═╡ 1071bfef-ab84-4831-b70f-a05d0686737b
begin
using DiscreteSim
    using PlutoUI
    using Plots
    using Statistics
    using Printf
    using Dates
end

# ╔═╡ 9d0ca023-c5aa-4985-bd0d-f0bfe9c4a153
begin
ROOT = dirname(@__DIR__)
end

# ╔═╡ eb83c3cd-0a65-46e7-8954-0ac16dcf1726
md"""
## The study, loaded from disk

`load_study` reads the JSON the pipeline wrote and turns it back into the
symbol-keyed records the package uses, so the notebook and the printed report
show the same numbers without re-running the study.
"""

# ╔═╡ 0b598566-aa05-4c42-b5bd-f868e80c21af
begin
bundle = load_study(ROOT);
end

# ╔═╡ 97ddcfe5-132a-464a-98a1-a569e14ee7b7
begin
TableOfContents()
end

# ╔═╡ 04cce292-ac4c-4d3c-893e-93ee2f9941af
md"""
## The section: *Reports*
"""

# ╔═╡ 2894d8a3-cb8d-4839-a4af-bd4ae3e6e94f
begin
HTML(preview_section(bundle, :reports))
end

# ╔═╡ 9e4bc692-e33c-4b68-a9bc-75be8e90adbc
md"""
## Everything the study produced

The pipeline writes its numbers to `data/`, its figures to `reports/figures/`, its
printouts to `reports/html/` and its PDFs to `reports/pdf/`. The cell below lists
them with their size, so a reader can see what the study is made of.
"""

# ╔═╡ 852c05a6-b912-41d4-b01e-bee0e075ae17
begin
file_rows = SymDict[]
    for kind in (:data, :figures, :html, :pdf)
        for p in get(bundle[:artifacts], kind, String[])
            path = joinpath(ROOT, String(p))
            isfile(path) || continue
            push!(file_rows, SymDict(:kind => kind, :file => relpath(path, ROOT),
                :bytes => filesize(path)))
        end
    end
    table_html(file_rows, [:kind, :file, :bytes]) |> HTML
end

# ╔═╡ 8ae3cf1f-c9ac-4af0-88a1-9463c77b48ca
md"""
## The whole report, in one PDF

A single call prints every section of the study as one document -- the same HTML the
sections above show, in order, with a table of contents.
"""

# ╔═╡ 644c6b16-461f-428b-953b-707382c21f4d
begin
full = print_report_pdf(bundle; root = ROOT)
    SymDict(:html => relpath(full[:html], ROOT), :pdf => relpath(full[:pdf], ROOT),
        :printed => full[:printed], :pdf_bytes => get(full, :pdf_bytes, 0))
end

# ╔═╡ 6293192e-8fae-4ba5-80e4-1f276d5084f8
begin
capability = pdf_capability()
    SymDict(:available => capability[:available], :browser => get(capability, :browser, :none))
end

# ╔═╡ 2cab5b0c-6652-4d25-a7d4-76db05440a68
begin
manifest = bundle[:manifest]
    (kind = :manifest, entries = length(manifest), status = get(manifest, :status, :ok),
        n_pdf = get(manifest, :n_pdf, 0), elapsed_seconds = get(manifest, :elapsed_seconds, 0.0))
end

# ╔═╡ bb911e32-7df4-49f0-93a0-14ed788e5563
md"""
## The printout, and its PDF

The cell below writes the section as a self-contained HTML printout and prints it
with a headless browser: `reports/html/notebook_reports.html` and
`reports/pdf/notebook_reports.pdf`. The notebook *is* the report -- the PDF is its
printout.
"""

# ╔═╡ bb537f55-7cf4-4b9e-8b6a-d3f48920d269
begin
println("run the study first if this file is missing: julia --project=. scripts/run_study.jl")
    print_section_pdf(bundle, :reports; root = ROOT)
end

# ╔═╡ c66a78c3-6bd1-4424-b8c5-abe3d1a6127d
md"""
---
*Generated by `DiscreteSim.jl` from `data/analysis.json` (seed
`$(get(get(bundle, :config, SymDict()), :seed, 0))`). Re-run
`julia --project=. scripts/run_study.jl` to refresh every number in this notebook.*
"""

# ╔═╡ Cell order:
# ╠═0a9ee0fc-ac97-4abd-86f3-d477f5200e0c
# ╠═74ba452f-3981-4c78-b251-aa58907663b2
# ╠═2ae2c8c0-19b7-4782-af2e-9abca3667242
# ╠═1071bfef-ab84-4831-b70f-a05d0686737b
# ╠═9d0ca023-c5aa-4985-bd0d-f0bfe9c4a153
# ╠═eb83c3cd-0a65-46e7-8954-0ac16dcf1726
# ╠═0b598566-aa05-4c42-b5bd-f868e80c21af
# ╠═97ddcfe5-132a-464a-98a1-a569e14ee7b7
# ╠═04cce292-ac4c-4d3c-893e-93ee2f9941af
# ╠═2894d8a3-cb8d-4839-a4af-bd4ae3e6e94f
# ╠═9e4bc692-e33c-4b68-a9bc-75be8e90adbc
# ╠═852c05a6-b912-41d4-b01e-bee0e075ae17
# ╠═8ae3cf1f-c9ac-4af0-88a1-9463c77b48ca
# ╠═644c6b16-461f-428b-953b-707382c21f4d
# ╠═6293192e-8fae-4ba5-80e4-1f276d5084f8
# ╠═2cab5b0c-6652-4d25-a7d4-76db05440a68
# ╠═bb911e32-7df4-49f0-93a0-14ed788e5563
# ╠═bb537f55-7cf4-4b9e-8b6a-d3f48920d269
# ╠═c66a78c3-6bd1-4424-b8c5-abe3d1a6127d
