#!/usr/bin/env julia
# =============================================================================
# make_notebooks.jl -- author the Pluto notebooks of the repository.
#
#   julia --project=. scripts/make_notebooks.jl
#
# The notebooks are deliverables, so they are written by a generator that knows
# Plutos file format exactly (unique cell ids, one `Cell order` section, the
# `@bind` mock for running outside Pluto) instead of by hand. The generated files
# are then plain, editable Pluto notebooks -- and `scripts/validate_notebooks.jl`
# plus `scripts/run_notebooks.jl` check them.
# =============================================================================
#
# The notebooks are deliverables, so they are written by a generator that knows
# Pluto's file format exactly (unique cell ids, one `Cell order` section, the
# `@bind` mock for running outside Pluto) instead of by hand. The generated files
# are then plain, editable Pluto notebooks.
using UUIDs
using Printf

const ROOT = normpath(joinpath(@__DIR__, ".."))
const NOTEBOOKS = joinpath(ROOT, "notebooks")

const BIND_MOCK = raw"""
# This Pluto notebook uses @bind for interactivity. When running this notebook outside of Pluto, the following 'mock version' of @bind gives bound variables a default value (instead of an error).
macro bind(def, element)
    quote
        local iv = try Base.loaded_modules[Base.PkgId(Base.UUID("6e696c72-6542-2067-7265-42206c756150"), "AbstractPlutoDingetjes")].Bonds.initial_value catch; b -> missing; end
        local el = $(esc(element))
        global $(esc(def)) = Core.applicable(Base.get, el) ? Base.get(el) : iv(el)
        el
    end
end
"""

"""One cell: markdown (`md"..."`) or code."""
md_cell(text) = string("md\"\"\"\n", strip(text), "\n\"\"\"")
code_cell(text) = string("begin\n", strip(join("    " .* split(strip(text), "\n"), "\n")),
    "\nend")

"""Write one notebook: header, cells, and the `Cell order` section Pluto expects."""
function write_notebook(name::AbstractString, cells::Vector{String})
    ids = [string(uuid4()) for _ in cells]
    io = IOBuffer()
    print(io, "### A Pluto.jl notebook ###\n# v0.20.23\n\nusing Markdown\nusing InteractiveUtils\n\n",
        BIND_MOCK)
    for (i, cell) in enumerate(cells)
        print(io, "\n# ", Char(0x2554), Char(0x2550), Char(0x2561), " ", ids[i], "\n",
            cell, "\n")
    end
    print(io, "\n# ", Char(0x2554), Char(0x2550), Char(0x2561), " Cell order:\n")
    for id in ids
        print(io, "# ", Char(0x2560), Char(0x2550), id, "\n")
    end
    path = joinpath(NOTEBOOKS, string(name, ".jl"))
    mkpath(NOTEBOOKS)
    write(path, String(take!(io)))
    return path
end

const USINGS = """
using DiscreteSim
using PlutoUI
using Plots
using Statistics
using Printf
using Dates
"""

const HEAD = [md_cell("""
# {TITLE}

{LEAD}

This notebook belongs to the study in this repository: it loads the artefacts the
pipeline produced (`data/analysis.json` and `reports/figures/*.png`), shows the
section of the report it is about, and prints that section to PDF in its last
cell. Nothing here is a copy of a number typed by hand -- every value comes from
the bundle, and the bundle comes from `scripts/run_study.jl`.
"""),
    md_cell("""
## The environment

The first cell activates `notebooks/Project.toml`, which has `DiscreteSim` (this
repository, developed in place) together with `PlutoUI` and `Plots`. Activating it
explicitly means the notebook runs the same environment interactively and headless
(`scripts/run_notebooks.jl`), with no package installation in the middle.
"""),
    code_cell("""
import Pkg
Pkg.activate(@__DIR__)"""),
    code_cell(USINGS),
    code_cell("ROOT = dirname(@__DIR__)"),
    md_cell("""
## The study, loaded from disk

`load_study` reads the JSON the pipeline wrote and turns it back into the
symbol-keyed records the package uses, so the notebook and the printed report
show the same numbers without re-running the study.
"""),
    code_cell("bundle = load_study(ROOT);"),
    code_cell("TableOfContents()")]

const PRINT_CELL = [md_cell("""
## The printout, and its PDF

The cell below writes the section as a self-contained HTML printout and prints it
with a headless browser: `reports/html/notebook_{KEY}.html` and
`reports/pdf/notebook_{KEY}.pdf`. The notebook *is* the report -- the PDF is its
printout.
"""),
    code_cell("""println("run the study first if this file is missing: julia --project=. scripts/run_study.jl")
print_section_pdf(bundle, :{KEY}; root = ROOT)"""),
    ## the closing note is a code cell, not a markdown one: `md"..."` interpolates
    ## everywhere *except* inside a code span, and this note wants the seed inside one
    code_cell("""
Markdown.parse(string("---\\n",
    "*Generated by `DiscreteSim.jl` from `data/analysis.json` (seed `",
    get(get(bundle, :config, SymDict()), :seed, 0),
    "`). Re-run `julia --project=. scripts/run_study.jl` to refresh every number ",
    "in this notebook.*"))""")]

"""Assemble one notebook from its markdown lead, its section key and its middle cells."""
function notebook_of(name, title, lead, key, middle)
    cells = String[]
    for c in HEAD
        push!(cells, replace(c, "{TITLE}" => title, "{LEAD}" => strip(lead)))
    end
    push!(cells, md_cell("## The section: *$(uppercasefirst(replace(string(key), '_' => ' ')))*"))
    push!(cells, code_cell("HTML(preview_section(bundle, :$key))"))
    append!(cells, middle)
    for c in PRINT_CELL
        push!(cells, replace(c, "{KEY}" => string(key)))
    end
    return write_notebook(name, cells)
end

## ---- 00: the overview -----------------------------------------------------------

const MANIFEST_CELL = [md_cell("""
## What the study produced

The manifest is the pipeline's own summary: the design, the verdicts and the
number of artefacts. It is what a scheduled job looks at.
"""),
    code_cell("bundle[:manifest]"),
    code_cell("bundle[:config]")]

const CATALOGUE_CELL = [md_cell("""
## The five models

Every model of the package answers one question, and they all record the same
kind of statistics -- which is why one report can print all of them.
"""),
    code_cell("""
rows = [SymDict(:model => name, :title => catalogue(name).title,
        :entity => catalogue(name).entity, :theory => catalogue(name).theory,
        :params => join(code_string.(catalogue(name).params), ", "))
    for name in MODELS]
table_html(rows, [:model, :title, :entity, :theory]) |> HTML""")]

## ---- 01: the engine -------------------------------------------------------------

const ENGINE_CELLS = [md_cell("""
## A live run, from scratch

The bundle shows the finished study; the cells below build a **new** simulation in
this notebook, with its own clock, calendar and processes, and check it against
the closed-form result of the same queue. Move the slider and re-run the cells
below it: the simulation and Erlang's formula move together.
"""),
    code_cell("""
@bind rate Slider(0.2:0.05:0.95; default = 0.8, show_value = true)"""),
    md_cell("""
### The model, in ten lines

An arrival process, one server per customer and a queue handled by the engine:
`request!` blocks the customer until a server is free, `hold!` occupies simulated
time and `release!` hands the server on.
"""),
    code_cell("""
params = model_params(:mmc, (arrival_rate = Float64(rate), servers = 2))
run = build_model(:mmc, params, SymDict(:seed => 20260101, :horizon => 4000.0, :trace => true))
warmup!(run, 400.0)
run!(run);
observed = observed_summary(run, :server)
theoretical = theory(:mmc; λ = params[:arrival_rate], μ = params[:service_rate],
    c = params[:servers])
validation = validate_against_theory(observed, theoretical;
    key_map = [:wait => :Wq, :queue_length => :Lq, :utilisation => :utilisation])
SymDict(:events => run.processed, :utilisation => utilisation(run[:server]),
    :wait_simulated => observed[:wait], :wait_erlang => theoretical[:Wq],
    :verdict => validation[:verdict])"""),
    md_cell("""
### The event trace

Every decision the engine made, in order: the trace is what the Gantt chart, the
throughput curve and every audit question are answered from. It also converts to a
table in one call, which is why the report can print a page of it.
"""),
    code_cell("rowtable = first(trace_rows(run.trace; limit = 14), 14)"),
    code_cell("fig_wip(run)"),
    md_cell("""
### The calendar, one event at a time

`step!` processes exactly one event, so an interactive session can look at the
system after every decision. `peek_event` says what is next without taking it.
"""),
    code_cell("""
next_events = [peek_event(run.calendar) for _ in 1:1]
(now = run.now, pending = pending(run), next = first(next_events))""")]

## ---- 02: queues and capacity ----------------------------------------------------

const QUEUE_CELLS = [md_cell("""
## Erlang C, live

The closed-form results the engine has to agree with are part of the package:
`theory(:mmc; λ, μ, c)` returns the whole stationary picture of an Erlang C queue.
Change the number of servers and watch the waiting time collapse.
"""),
    code_cell("""
@bind servers Slider(1:8; default = 2, show_value = true)"""),
    code_cell("""
λ = 0.75
rows = [theory(:mmc; λ = λ, μ = 0.5, c = c) for c in 1:Int(servers)
        if λ / (0.5 * c) < 1]                    # only the stable configurations
table_html([SymDict(:servers => r[:c], :rho => r[:rho], :pw => r[:pw], :Lq => r[:Lq],
        :Wq => r[:Wq], :W => r[:W], :L => r[:L]) for r in rows],
    [:servers, :rho, :pw, :Lq, :Wq, :W, :L]) |> HTML"""),
    md_cell("""
### The same system, simulated

The configuration on the slider, run `n` times, with the interval of the mean
waiting time -- and Erlang C for comparison. A configuration whose offered load
reaches the capacity (ρ ≥ 1) has no steady state, so the notebook says so instead
of producing a number.
"""),
    code_cell("""
factor = model_params(:mmc, (arrival_rate = λ, service_rate = 0.5, servers = Int(servers)))
stable = λ / (0.5 * Int(servers)) < 1
study = stable ? experiment(opts -> build_model(:mmc, factor, opts),
    ExperimentConfig(replications = 6, horizon = 4000.0, warmup = 400.0);
    name = :mmc_live) : nothing;
nothing"""),
    code_cell("""
ci = study === nothing ? nothing : metric_ci(study, :wait_mean)
theory_wq = stable ? theory(:mmc; λ = λ, μ = 0.5, c = Int(servers))[:Wq] : NaN
SymDict(:servers => Int(servers), :rho => round(λ / (0.5 * Int(servers)), digits = 3),
    :stable => stable, :wait_mean => ci === nothing ? NaN : ci[:mean],
    :half_width => ci === nothing ? NaN : ci[:half_width], :erlang_wq => theory_wq,
    :covered => ci === nothing ? false : ci[:lo] <= theory_wq <= ci[:hi])"""),
    code_cell("study === nothing ? nothing : fig_convergence(study)")]

## ---- 03: the models -------------------------------------------------------------

const MODEL_CELLS = [md_cell("""
## Every model, one at a time

Pick a model, build it from its **calibrated** parameters (the ones the data layer
produced) and run it: the metrics come from the engine, and the last row is the
cross-check — Erlang C for the queues, Little's law for the rest.
"""),
    code_cell("""
@bind choice Select([code_string(m) => m for m in MODELS]; default = :machine_shop)"""),
    code_cell("""
chosen = model_params_from_calibration(bundle[:calibration], choice)
sample = build_model(choice, chosen,
    SymDict(:seed => get(bundle[:config], :seed, 20260101), :horizon => 4000.0,
        :warmup => 400.0, :trace => true))
run!(sample);
servers = [r for (_, r) in sample.resources if r isa DiscreteSim.Resource]
SymDict(:model => choice, :validation => validate_model(sample, choice, chosen)[:verdict],
    :completed => count_of(sample[:completed]),
    :mean_utilisation => round(sum(utilisation(r) for r in servers) /
        max(length(servers), 1), digits = 3))"""),
    code_cell("""
rows = [SymDict(:metric => get(r, :name, :unknown), :kind => get(r, :kind, :unknown),
        :mean => get(r, :mean, NaN), :unit => get(r, :unit, :count))
        for r in statistics_table(sample)]
table_html(rows, [:metric, :kind, :mean, :unit]) |> HTML"""),
    code_cell("fig_utilisation(sample)"),
    code_cell("""
from_study = metric_ci(bundle[:models][choice], :throughput)
(choice = choice, source = :from_the_study,
    throughput = from_study === nothing ? NaN : from_study[:mean])""")]

## ---- 04: experiments ------------------------------------------------------------

const EXPERIMENT_CELLS = [md_cell("""
## Warmup: how long the transient lasts

Welch's procedure, run live on a small queue: the moving average of the response
settles, and the time where it settles is the warmup the study should use.
"""),
    code_cell("""
demo = model_params(:mmc, (arrival_rate = 0.85, service_rate = 1.0, servers = 1))
warming = warmup_analysis(opts -> build_model(:mmc, demo, opts),
    ExperimentConfig(replications = 5, horizon = 3000.0); series = :wip, window = 15)
SymDict(:suggested_warmup => warming[:warmup], :plateau => warming[:plateau],
    :band => warming[:band])"""),
    code_cell("fig_warmup(warming)"),
    md_cell("""
## Replications and intervals

One run of a queue gives a number; several give a number *and* an interval. The
cell below runs six replications, reports the interval of the mean waiting time,
and asks how many replications a 5% relative precision would need.
"""),
    code_cell("""
config = ExperimentConfig(replications = 6, horizon = 3000.0, warmup = 300.0)
replicated = experiment(opts -> build_model(:mmc, demo, opts), config; name = :mmc_ci);
wait_ci = metric_ci(replicated, :wait_mean)
SymDict(:mean => wait_ci[:mean], :half_width => wait_ci[:half_width],
    :relative_half_width => wait_ci[:relative_half_width],
    :needed_for_5pct => required_replications(metric_series(replicated, :wait_mean)))"""),
    md_cell("""
## Common random numbers

Two scenarios run with the *same* seeds in the same replication are paired, so the
difference of their means has a much tighter interval than either mean: that is
what makes a comparison of two designs decisive.
"""),
    code_cell("""
paired = compare_scenarios([
        :baseline => (opts -> build_scenario(:mmc, :baseline, opts)),
        :capacity_up => (opts -> build_scenario(:mmc, :capacity_up, opts))],
    config; objective = :wait_mean);
comparison = first(filter(c -> c[:metric] === :wait_mean, paired[:comparisons]))
SymDict(:scenario => comparison[:label], :difference => comparison[:difference],
    :half_width => comparison[:half_width],
    :variance_removed => comparison[:variance_reduction],
    :verdict => comparison[:verdict])"""),
    code_cell("bundle[:batch_means]")]

## ---- 05: the calibration ---------------------------------------------------------

const CALIBRATION_CELLS = [md_cell("""
## Fitting by hand

The pipeline fitted every series of the plant history. Here is the same work done
in the open: take a sample, fit four families by maximum likelihood, and let the
Kolmogorov--Smirnov statistic decide which one can be defended.
"""),
    code_cell("""
truth = SymDict(:mean => 3.0, :shape => 4.0)
γ_sample = let σ = Sim(:fit_demo; seed = 20260101)
    sample_n(σ, :demo, :gamma => (truth[:shape], truth[:mean] / truth[:shape]), 400)
end
best_fit(γ_sample; kinds = (:exponential, :lognormal, :gamma, :weibull))[:kind]"""),
    code_cell("""
fitted = best_fit(γ_sample)
table_html([SymDict(:family => k, :rank => rank[:rank], :ks_stat => rank[:ks_stat],
        :ks_p => rank[:ks_p], :aic => rank[:aic]) for (k, rank) in fitted[:ranking]],
    [:family, :rank, :ks_stat, :ks_p, :aic]) |> HTML"""),
    code_cell("fig_calibration(γ_sample, fitted; series = :demo)"),
    md_cell("""
## How uncertain is a parameter?

The bootstrap resamples the observations, refits and reports the percentiles: that
is the interval a calibration report quotes for every fitted parameter.
"""),
    code_cell("""
interval = bootstrap_ci(γ_sample, fitted[:kind], 1; reps = 80)
SymDict(:family => fitted[:kind], :parameter => fitted[:params][1],
    :median => interval[:median], :lo => interval[:lo], :hi => interval[:hi])"""),
    md_cell("""
## What the plant data says about the model

`calibrate` does all of the above for every measured series, and
`model_params_from_calibration` turns the result into model parameters -- the ones
the pipeline then simulated.
"""),
    code_cell("""
from_data = bundle[:calibration][:parameters]
SymDict(:arrival_rate => get(from_data, :arrival_rate, NaN),
    :service_rate => get(from_data, :service_rate, NaN),
    :mtbf => get(from_data, :mtbf, NaN), :mttr => get(from_data, :mttr, NaN),
    :availability => get(from_data, :availability, NaN))"""),
    code_cell("bundle[:history][:summary]")]

## ---- 06: offline and online -----------------------------------------------------

const ONLINE_CELLS = [md_cell("""
## The fallback chain, live

The data layer never fails. Ask for the periodic feed and it walks down the chain:
the online source, the local copy of the same feed, the last cached reply, and
finally offline with whatever the model already knows.
"""),
    code_cell("""
reachable = fetch_online(OnlineConfig())
SymDict(:url => reachable[:url], :status => reachable[:status], :source => reachable[:source],
    :freshness => reachable[:freshness], :attempts => reachable[:attempts],
    :age_days => get(reachable, :age_days, NaN))"""),
    code_cell("""
feed_file = joinpath(ROOT, "data", "online_feed.json")
blocked = fetch_online(OnlineConfig(url = "http://127.0.0.1:9/nothing",
    local_file = feed_file, timeout = 1.0, retries = 0))
counts = get(blocked, :observations, nothing)
SymDict(:status => blocked[:status], :source => blocked[:source],
    :fallback => get(blocked, :fallback, :none),
    :series => counts === nothing ? 0 : length(counts))"""),
    code_cell("""
offline = fetch_online(OnlineConfig(url = "http://127.0.0.1:9/nothing",
    local_file = joinpath(ROOT, "data", "missing.json"), timeout = 1.0, retries = 0,
    cache_dir = joinpath(ROOT, "tmp", "empty_cache")))
SymDict(:status => offline[:status], :source => offline[:source],
    :freshness => offline[:freshness])"""),
    md_cell("""
## The decision the feed justifies

A reevaluation round recalibrates from the freshest observations, compares them
with the model in use (relative change per parameter, and a two-sample
Kolmogorov--Smirnov test per series) and writes a verdict. The log is the audit
trail: when the model was checked, against what, and what was decided.
"""),
    code_cell("""
record = reevaluate(bundle[:calibration]; cfg = OnlineConfig(local_file = feed_file),
    model = Sym(get(bundle, :model, :mmc)), plan = ReevaluationPlan(7, :days),
    log_path = joinpath(ROOT, "data", "reevaluation_log.json"));
SymDict(:verdict => record[:verdict], :reason => record[:reason],
    :source => record[:source], :worst_change => record[:worst_change],
    :ks_tests => length(record[:ks]))"""),
    code_cell("""
log_rows = reevaluation_log(joinpath(ROOT, "data", "reevaluation_log.json"))
(last = isempty(log_rows) ? SymDict(:note => :empty) : feed_row(log_rows[end]),
    entries = length(log_rows))"""),
    code_cell("""
plan = ReevaluationPlan(7, :days)
SymDict(:plan => describe_plan(plan), :days => plan_days(plan),
    :due_after_3_days => due(plan, timestamp(Dates.now() - Dates.Day(3)), timestamp()),
    :due_after_30_days => due(plan, timestamp(Dates.now() - Dates.Day(30)), timestamp()))""")]

## ---- 07: the artefacts ----------------------------------------------------------

const ARTIFACT_CELLS = [md_cell("""
## Everything the study produced

The pipeline writes its numbers to `data/`, its figures to `reports/figures/`, its
printouts to `reports/html/` and its PDFs to `reports/pdf/`. The cell below lists
them with their size, so a reader can see what the study is made of.
"""),
    code_cell("""
file_rows = SymDict[]
for kind in (:data, :figures, :html, :pdf)
    for p in get(bundle[:artifacts], kind, String[])
        path = joinpath(ROOT, String(p))
        isfile(path) || continue
        push!(file_rows, SymDict(:kind => kind, :file => relpath(path, ROOT),
            :bytes => filesize(path)))
    end
end
table_html(file_rows, [:kind, :file, :bytes]) |> HTML"""),
    md_cell("""
## The whole report, in one PDF

A single call prints every section of the study as one document -- the same HTML the
sections above show, in order, with a table of contents.
"""),
    code_cell("""
full = print_report_pdf(bundle; root = ROOT)
SymDict(:html => relpath(full[:html], ROOT), :pdf => relpath(full[:pdf], ROOT),
    :printed => full[:printed], :pdf_bytes => get(full, :pdf_bytes, 0))"""),
    code_cell("""
capability = pdf_capability()
SymDict(:available => capability[:available], :browser => get(capability, :browser, :none))"""),
    code_cell("""
manifest = bundle[:manifest]
(kind = :manifest, entries = length(manifest), status = get(manifest, :status, :ok),
    n_pdf = get(manifest, :n_pdf, 0), elapsed_seconds = get(manifest, :elapsed_seconds, 0.0))""")]

## ---- generate every notebook -----------------------------------------------------

const NOTEBOOKS_TO_WRITE = [
    ("00_Study_Overview", "The study at a glance",
        "What was simulated, with which design, and what the engine concluded.",
        :overview, vcat(MANIFEST_CELL, CATALOGUE_CELL)),
    ("01_The_Engine", "Inside the event engine",
        "The calendar, the processes and the trace: how a discrete-event simulator decides what happens next.",
        :engine, ENGINE_CELLS),
    ("02_Queues_and_Capacity", "Queues, Erlang and capacity",
        "A simulation is only credible when it agrees with queueing theory, and only useful when it says how much capacity to install.",
        :queues, QUEUE_CELLS),
    ("03_The_Models", "The five models",
        "A service pool, a transfer line, a job shop, an inventory position and a contact centre, all on one engine.",
        :models, MODEL_CELLS),
    ("04_Experiments_and_Confidence", "Experiments, warmup and confidence",
        "Why one run is not an answer: replications, Welch's warmup, batch means and common random numbers.",
        :experiments, EXPERIMENT_CELLS),
    ("05_Calibration", "Calibration from plant data",
        "Where the numbers in the model come from, and how well they fit.",
        :calibration, CALIBRATION_CELLS),
    ("06_Offline_and_Online", "Offline first, online for periodic reevaluation",
        "A feed that never breaks the pipeline, and the decision it justifies.",
        :online, ONLINE_CELLS),
    ("07_Artefacts_and_PDF", "Artefacts and the printed report",
        "Every file the study produced, and the one call that prints the whole report.",
        :reports, ARTIFACT_CELLS),
]

for (name, title, lead, key, middle) in NOTEBOOKS_TO_WRITE
    path = notebook_of(name, title, lead, key, middle)
    @printf("%-36s %5d lines\n", relpath(path, ROOT), length(readlines(path)))
end


